### ISSUE TITLE
Hello, how to use your code? And what dependencies are needed?

### ISSUE THREAD

**Issue by deepmo24** [jjbouza/cublas-inverse-pytorch#1]
Hello, thank you for your contribution. I am very interested in your code.

Recently I find torch.inverse() is very slow in GPU(even slower than CPU) and is searching for solution.
 And your code seems can accelerate inverse() in GPU! I am happy and try your code, but I meet some errors when runing 'python setup.py install' like this:
`cuda_inverse_pytorch.cpp:1:29: fatal error: torch/extension.h: No such file or directory`

Maybe I lack some dependencies, can you help me out? Thank you!

**Comment by deepmo24** [comment]
I change CUDA directory "/usr/local/cuda-10.0"  in 'setup.py' and the above issue is solved. 

However, I encounter another issue now, like this:

`cuda_inverse_pytorch.cpp:89:31: error: invalid conversion from 'float**' to 'const float**' [-fpermissive]`


The whole console output:
```
running install
running bdist_egg
running egg_info
writing cuda_batch_inverse.egg-info/PKG-INFO
writing dependency_links to cuda_batch_inverse.egg-info/dependency_links.txt
writing top-level names to cuda_batch_inverse.egg-info/top_level.txt
reading manifest file 'cuda_batch_inverse.egg-info/SOURCES.txt'
writing manifest file 'cuda_batch_inverse.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'cuda_batch_inverse' extension
gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/cuda-9.0/include -I/opt/conda/lib/python3.6/site-packages/torch/lib/include -I/opt/conda/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/lib/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/lib/include/THC -I/opt/conda/include/python3.6m -c cuda_inverse_pytorch.cpp -o build/temp.linux-x86_64-3.6/cuda_inverse_pytorch.o -g -DDEBUG -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=cuda_batch_inverse -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
cuda_inverse_pytorch.cpp: In function 'at::Tensor torch_cublas_inverse::batch_inverse_forward(at::Tensor)':
cuda_inverse_pytorch.cpp:89:31: error: invalid conversion from 'float**' to 'const float**' [-fpermissive]
                     batch_size);
                               ^
In file included from /usr/local/cuda-9.0/include/cublas_v2.h:65:0,
                 from /opt/conda/lib/python3.6/site-packages/torch/lib/include/THC/THCGeneral.h:17,
                 from /opt/conda/lib/python3.6/site-packages/torch/lib/include/THC/THC.h:4,
                 from cuda_inverse_pytorch.cpp:2:
/usr/local/cuda-9.0/include/cublas_api.h:2596:39: note:   initializing argument 3 of 'cublasStatus_t cublasSgetriBatched(cublasHandle_t, int, const float**, int, const int*, float**, int, int*, int)'
 CUBLASAPI cublasStatus_t CUBLASWINAPI cublasSgetriBatched(cublasHandle_t handle,
                                       ^~~~~~~~~~~~~~~~~~~
error: command 'gcc' failed with exit status 1
```

**Comment by jjbouza** [comment]
Hi,

I am currently working on this so it might be changing a lot. Please try the most recent commit and see if that helps. That being said, I am seeing reasonable speed increases from using the cuBLAS backend and the current commit builds on my system with:
CUDA 10
gcc 7.3.0
Pytorch 1.1 

Let me know if you can install the latest version with those dependencies. If not I will look into it further.

**Comment by deepmo24** [comment]
Hi, 

I successfully install with dependencies:
CUDA 10
gcc 5.4.0
Pytorch 1.1

And I also see a large speed increase with your cuda_inverse(). However, there is a  question that the function  cuda_inverse() returns '<class 'cuda_inverse.cuda_inverse'>' object, not a Pytorch Tensor.  So I can't use the returned value with other Pytorch code.

Any suggesion? Thank you!

**Comment by jjbouza** [comment]
cuda_inverse.apply(A) would work. I just pushed an update to fix this though, so cuda_inverse(A) should be okay now. Thank you!

**Comment by jjbouza** [comment]
Let me know if you have any other questions, I'll close this for now.

**Comment by deepmo24** [comment]
Thank you very much.

the code now return the Tensor. However, It seems the speed gains decrease. (now it speeds up less than 2x )

I have another question. Now cuda_inverse() can't be applied to Tensor like torch.rand(1024,1024). I wonder if you can make it work. Thank you!

**Comment by jjbouza** [comment]
Because before you weren't computing the inverse, you were just returning the cuda_inverse object. The speed gains will be marginal since the native pytorch library for batch matrix inverse (MAGMA) is already pretty good. You will mostly get better performance for small matrix size with lots of batches.

As for your second question, I will take a look at that later, but for now you can just do

```python
cuda_inverse(torch.rand(1024,1024).unsqueeze(0))
```

**Comment by deepmo24** [comment]
Thank you for your patient answer.

Actually I find torch.inverse() is not good enough when the Tensor is on GPU, it is even slower than that on CPU. I tested it in my program before. In my neural network model, there is an 'inverse' operation to compute during training, and I find this operation reduces GPU utilization (being the bottleneck of training speed). So this is why I try to find a solution to accelerate inverse() on GPU.

You can test it to see if I am right.  In fact I am quite confused why torch.inverse() is so slow on GPU (compared to CPU)? I wonder if you can provide some help. Thank you!

**Comment by jjbouza** [comment]
This will depend on a lot of factors. For small batch size or large matrices the CPU will probably be better. I don't know much about the MAGMA internals of the native torch.inverse operations, so I would recommend you open an issue in PyTorch if you think it is unreasonably slow (on my machine it is about 5% slower than cuBLAS on average).

**Comment by deepmo24** [comment]
Thank you for your suggestion! You're too kind.
